name: Build OnePlus KSU Kernel
on:
  workflow_dispatch:
    inputs:
      TAG:
        required: true
        type: choice
        description: 'Select Branch'
        options:
        - oneplus/sm8650
        - oneplus/sm7550
        - oneplus/sm7675
        - oneplus/sm8550
        - oneplus/sm8750
        default: 'oneplus/sm8650'
      MFT:
        required: true
        description: 'Select Manifest'
        default: 'oneplus12_v'
      ENABLE_KSU:
        required: true
        type: boolean
        default: true
        description: 'Enable KernelSU'

jobs:
  build:
    name: Build OnePlus Kernel - ${{ inputs.TAG }}
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
    steps:
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 8192
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Download Kernel Source
      run: |
        sudo apt-get remove firefox -y
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install repo -y
        cd $GITHUB_WORKSPACE
        git config --global user.name "wizxy"
        git config --global user.email wizxy@users.noreply.github.com
        mkdir android-kernel && cd android-kernel
        repo init --depth=1 --u https://github.com/OnePlusOSS/kernel_manifest.git -b ${{ inputs.TAG }} -m ${{ inputs.MFT }}.xml --repo-rev=v2.16
        repo --trace sync -q -c -j$(nproc --all) --no-tags
        rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_*

    - name: Setup KernelSU
      if: inputs.ENABLE_KSU == true
      run: |
        cd $GITHUB_WORKSPACE/android-kernel/kernel_platform
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
        cd ./KernelSU-Next/kernel
        sed -i 's/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=12293/' ./Makefile
        cd ../../

    - name: Setup SUSFS
      if: inputs.ENABLE_KSU == true
      run: |
        cd $GITHUB_WORKSPACE/android-kernel/kernel_platform
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
        cp ./susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
        cp ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./common/
        cp ./susfs4ksu/kernel_patches/fs/susfs.c ./common/fs/
        cp ./susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
        cd ./KernelSU-Next/
        patch -p1 < 10_enable_susfs_for_ksu.patch || true
        cd ../common
        patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true

    - name: Apply Additional Patches
      if: inputs.ENABLE_KSU == true
      run: |
        cd $GITHUB_WORKSPACE/android-kernel/kernel_platform
        git clone https://github.com/TheWildJames/kernel_patches.git
        cd common
        cp ../kernel_patches/69_hide_stuff.patch ./
        patch -p1 -F 3 < 69_hide_stuff.patch || true
        sed -i '/obj-\$(CONFIG_KSU_SUSFS_SUS_SU) += sus_su.o/d' ./fs/Makefile
        cd ..
        cp ./kernel_patches/apk_sign.c_fix.patch ./
        patch -p1 -F 3 < apk_sign.c_fix.patch || true
        cp ./kernel_patches/core_hook.c_fix.patch ./
        patch -p1 --fuzz=3 < ./core_hook.c_fix.patch || true
        cp ./kernel_patches/selinux.c_fix.patch ./
        patch -p1 -F 3 < selinux.c_fix.patch || true
        cp ./kernel_patches/Makefile_fix.patch ./
        patch -p1 --fuzz=3 < ./Makefile_fix.patch || true

    - name: Configure Kernel
      if: inputs.ENABLE_KSU == true
      run: |
        cd $GITHUB_WORKSPACE/android-kernel/kernel_platform
        echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> ./common/arch/arm64/configs/gki_defconfig
        
        sed -i '2s/check_defconfig//' ./common/build.config.gki
        sed -i "s/-dirty//g" ./common/scripts/setlocalversion
        sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
        sed -i "\$s/\$res/-android14-11-o-gd44351ca26e5/" ./common/scripts/setlocalversion
           
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: oneplus-kernel-${{ inputs.TAG }}
        max-size: 2G

    - name: Build Kernel
      run: |
        cd $GITHUB_WORKSPACE/android-kernel
        ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki

    - name: Prepare AnyKernel3
      run: |
        OUTDIR=android-kernel/out/dist/
        git clone https://github.com/Kernel-SU/AnyKernel3
        rm -rf ./AnyKernel3/.git
        ls $OUTDIR
        cp $OUTDIR/Image ./AnyKernel3/

    - name: Upload Boot
      uses: actions/upload-artifact@v4
      with:
        name: Boot-${{ inputs.MFT }}
        path: android-kernel/out/dist/boot.img
        
    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-${{ inputs.MFT }}
        path: ./AnyKernel3/*
